-- Add jersey number and live game tracking fields
ALTER TABLE bets ADD COLUMN IF NOT EXISTS jersey_number TEXT;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS game_status TEXT DEFAULT 'SCHEDULED';
ALTER TABLE bets ADD COLUMN IF NOT EXISTS home_score INTEGER;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS away_score INTEGER;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS game_clock TEXT;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS live_stat REAL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS live_model_prob REAL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS settled_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_bets_game_status ON bets(game_status);
